// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5LBREgplG9oqWd8oOlHYmBFqQIixlcRQ',
    appId: '1:108195149647:web:b5486d7c3f7fbd560ff73a',
    messagingSenderId: '108195149647',
    projectId: 'nutrimind-514e7',
    authDomain: 'nutrimind-514e7.firebaseapp.com',
    storageBucket: 'nutrimind-514e7.firebasestorage.app',
    measurementId: 'G-25E3C0VVCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCneBhfGp98dSFhbV7vEtgGcfjO_w4OLnM',
    appId: '1:108195149647:android:d2d94d2dc8fc5a7a0ff73a',
    messagingSenderId: '108195149647',
    projectId: 'nutrimind-514e7',
    storageBucket: 'nutrimind-514e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLWfJrHOoAcLfPyl1AUYoD11zGRrpUtek',
    appId: '1:108195149647:ios:9751a800bdb82f6a0ff73a',
    messagingSenderId: '108195149647',
    projectId: 'nutrimind-514e7',
    storageBucket: 'nutrimind-514e7.firebasestorage.app',
    iosBundleId: 'com.example.nutrimind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLWfJrHOoAcLfPyl1AUYoD11zGRrpUtek',
    appId: '1:108195149647:ios:9751a800bdb82f6a0ff73a',
    messagingSenderId: '108195149647',
    projectId: 'nutrimind-514e7',
    storageBucket: 'nutrimind-514e7.firebasestorage.app',
    iosBundleId: 'com.example.nutrimind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5LBREgplG9oqWd8oOlHYmBFqQIixlcRQ',
    appId: '1:108195149647:web:f85e122f5366dace0ff73a',
    messagingSenderId: '108195149647',
    projectId: 'nutrimind-514e7',
    authDomain: 'nutrimind-514e7.firebaseapp.com',
    storageBucket: 'nutrimind-514e7.firebasestorage.app',
    measurementId: 'G-1E6YYJ2NLK',
  );
}
